### ISSUE TITLE
Net::OpenTimeout error when fetching the blog posts

### ISSUE THREAD

**Issue by ognarb** [feedreader/pluto#25]
here is my backtrace:

```
08:03:07  /usr/lib/ruby/2.5.0/net/protocol.rb:41:in `ssl_socket_connect': Net::OpenTimeout (Net::OpenTimeout)
08:03:07  	from /usr/lib/ruby/2.5.0/net/http.rb:985:in `connect'
08:03:07  	from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
08:03:07  	from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
08:03:07  	from /usr/lib/ruby/2.5.0/net/http.rb:1458:in `request'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/fetcher-0.4.5/lib/fetcher/worker.rb:203:in `get_response'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/fetcher-0.4.5/lib/fetcher/worker.rb:56:in `get'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-feedfetcher-0.1.5/lib/pluto/feedfetcher/cond_get_with_cache.rb:34:in `fetch'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-update-1.6.3/lib/pluto/update/feed_refresher.rb:57:in `refresh_feed_worker'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-update-1.6.3/lib/pluto/update/feed_refresher.rb:49:in `block in refresh_feeds_for'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:85:in `each'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:85:in `each'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-update-1.6.3/lib/pluto/update/feed_refresher.rb:48:in `refresh_feeds_for'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-1.3.4/lib/pluto/cli/updater.rb:51:in `update_for'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-1.3.4/lib/pluto/cli/updater.rb:31:in `run'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:232:in `block (3 levels) in <top (required)>'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:208:in `each'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:208:in `block (2 levels) in <top (required)>'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/gli-2.19.0/lib/gli/command_support.rb:131:in `execute'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/gli-2.19.0/lib/gli/app_support.rb:296:in `block in call_command'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/gli-2.19.0/lib/gli/app_support.rb:309:in `call_command'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/gli-2.19.0/lib/gli/app_support.rb:83:in `run'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:390:in `<top (required)>'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-1.3.4/lib/pluto.rb:24:in `main'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/gems/pluto-1.3.4/bin/pluto:5:in `<top (required)>'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/bin/pluto:23:in `load'
08:03:07  	from /home/user/workspace/Website_planet-kde-org/vendor/ruby/2.5.0/bin/pluto:23:in `<main>'
```

**Comment by geraldb** [comment]
Thanks for reporting the error when fetching blog post.  Is this a "sporadic" error e.g. only happens once in a while  or is it always and every time?   If you can add the --verbose switch on the command line it should tell you more e.g. is it the first web feed or which one is causing the error? 

Note: due to Corona COVID-19 I'm currently mostly offline (and sorry don't expect fast response) - thanks for your patience. stay healthy,

**Comment by geraldb** [comment]
I cannot reproduce with my test feeds but it looks like Net::OpenTimeout is another unhandled exception - I added Net::OpenTimeout to the rescue clause and it should get handled and logger but not abort. Please, update to the latest pluto-feedfetcher gem (v.0.1.6), see <https://rubygems.org/gems/pluto-feedfetcher>.

**Comment by ognarb** [comment]
Thanks a lot, the new version now run on our server. :heart_eyes:  I will report if the problem reappear.
