### ISSUE TITLE
Issue with rexml/Document

### ISSUE THREAD

**Issue by luke-biel** [feedreader/pluto#26]
`uname -a`: `Linux LaptopLB 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
```
>> pluto u planet.ini 
Traceback (most recent call last):
	24: from /home/luke-biel/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
	23: from /home/luke-biel/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
	22: from /home/luke-biel/.rvm/gems/ruby-2.5.5/bin/pluto:23:in `<main>'
	21: from /home/luke-biel/.rvm/gems/ruby-2.5.5/bin/pluto:23:in `load'
	20: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/pluto-1.3.4/bin/pluto:3:in `<top (required)>'
	19: from /home/luke-biel/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	18: from /home/luke-biel/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/pluto-1.3.4/lib/pluto.rb:4:in `<top (required)>'
	16: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	15: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	14: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	13: from /home/luke-biel/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /home/luke-biel/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/pluto-update-1.6.4/lib/pluto/update.rb:3:in `<top (required)>'
	10: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	 9: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	 8: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	 7: from /home/luke-biel/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /home/luke-biel/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/opmlparser-1.0.0/lib/opmlparser.rb:4:in `<top (required)>'
	 4: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	 3: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	 2: from /home/luke-biel/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	 1: from /home/luke-biel/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/luke-biel/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rexml/Document (LoadError)
```
This happens for me on my 2 development linux machines, Manually changing `rexml/Document` to lowercase in *opmlparser* solves the issue,

I haven't seen anyone else complaints about it, so I'd prefer to get feedback before opening PR. Maybe it's a setup issue?

**Comment by geraldb** [comment]
Thanks for reporting. Good catch. Sorry for the trouble - I assume you are right with changing rexml/document - it's my fault because shame on me I'm currently using a windows computer (and windows doesn't care about case-sensitivity in files).  I try to test if it works with all lowe-cash. Thanks again for reporting. Keep it up. NOTE: Due to corona covid-19 I'm currently not at "full-speed" and always online or "working". Stay save. Stay home. Wash hands. Cheers.

**Comment by luke-biel** [comment]
Case insensitivity was my first guess, but didn't want to rush into conclusions since I've seen other open issues from linux users without such problem. I'll open a PR so you can test it.

**Comment by geraldb** [comment]
Thanks for reporting back and your help. I try to get an updated gem out later this week (or tomorrow, that is, Wednesday / Thursday). Cheers. Prost.

**Comment by geraldb** [comment]
@luke-biel  Thanks again. A new updated gem is now available with your changes / fix - <https://rubygems.org/gems/opmlparser/versions/1.0.1>. Cheers. Prost.
